[/]
active-hint-border-radius=uint32 0
active-hint-border-width=uint32 1
active-hint-overlay-color-rgba='auto'
active-hint-overlay-enabled=false
cleared-system-bindings='{"focus-left":[{"schema_id":"org.gnome.desktop.wm.keybindings","key":"minimize","accelerator":"<Super>h","expected":[]}],"focus-down":[{"schema_id":"org.gnome.shell.keybindings","key":"shift-overview-down","accelerator":"<Super><Alt>Down","expected":[]}],"focus-up":[{"schema_id":"org.gnome.shell.keybindings","key":"shift-overview-up","accelerator":"<Super><Alt>Up","expected":[]}],"pop-workspace-up":[{"schema_id":"org.gnome.desktop.wm.keybindings","key":"move-to-monitor-up","accelerator":"<Super><Shift>Up","expected":[]}],"pop-workspace-down":[{"schema_id":"org.gnome.desktop.wm.keybindings","key":"move-to-monitor-down","accelerator":"<Super><Shift>Down","expected":[]}]}'
gap-inner=uint32 1
gap-outer=uint32 1
hide-panel-icon=true
panel-transparency=false
quick-settings-toggle=true
show-close-button=true
show-overview-button-in-indicator=false
smart-gaps=false
snap-to-grid=true
theme-consistency-style='sharp'
tile-by-default=true
tile-enter=['<Super><Shift>Return']
toggle-tiling=['<Super>t']
workspace-animation-style='none'
workspace-indicator-border-radius=uint32 0
workspace-indicator-position='left'
workspace-indicator-style='numbers'
workspace-number-indicator=true
